runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  mime_type: application/octet-stream

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /images
  static_dir: images

- url: /bower_components
  static_dir: bower_components
  mime_type: application/octet-stream

skip_files:
- ^(.*/)?\.jade$
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?